import Head from "next/head";
import { Inter } from "@next/font/google";
import { HealthInfo, Hero, Navbar, StaticBar, Workout } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Gym Baran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-10">
          <Navbar />
          <Hero />
          <HealthInfo />
          <StaticBar />
          <Workout />
        </div>
      </main>
    </>
  );
}
